import json

def main():
    nb_path = "rnd_1_ticks_and_rate.ipynb"
    with open(nb_path, "r", encoding="utf-8") as f:
        nb = json.load(f)
        
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            # Identify core evaluator cell by matching key lines
            source_text = "".join(cell["source"])
            if "def evaluate_stability" in source_text and "generate_dummy_yaml" in source_text:
                print("Updating evaluator cell (evaluate_stability)...")
                # We need to replace the generate_dummy_yaml call to include cg_pkl and ddm_pkl
                new_source = [
                    "import io\n",
                    "import contextlib\n",
                    "import gc\n",
                    "import numpy as np\n",
                    "\n",
                    "# If the parallel runner deadlocks in Jupyter on your test PC, set this to False\n",
                    "USE_PARALLEL = True \n",
                    "\n",
                    "def evaluate_stability(spt, ticks, num_routes, pass_rate, reps=REPLICATIONS):\n",
                    "    cg_pkl = \"rnd/pkl/profile_p1.pkl\"\n",
                    "    ddm_pkl = \"rnd/pkl/ddm_8am.pkl\"\n",
                    "    \n",
                    "    batch_yaml = f\"rnd/configs/temp_qa_spt{spt}_tk{ticks}.yaml\"\n",
                    "    \n",
                    "    # --- SETUP PHASE (MUTED) ---\n",
                    "    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):\n",
                    "        generate_dummy_yaml(\n",
                    "            export_loc=batch_yaml,\n",
                    "            **{\n",
                    "                \"simulation.seconds_per_tick\": spt,\n",
                    "                \"simulation.num_ticks\": ticks,\n",
                    "                \"simulation.spawn_rate_per_hour\": pass_rate,\n",
                    "                \"cg_pkl\": cg_pkl,\n",
                    "                \"ddm_pkl\": ddm_pkl\n",
                    "            }\n",
                    "        )\n",
                    "        \n",
                    "        G_city = reuse_citygraph(cg_pkl)\n",
                    "        demand_sampler = reuse_ddm(ddm_pkl)\n",
                    "        \n",
                    "        envs = []\n",
                    "        for rep in range(reps):\n",
                    "            # OPTIMIZATION: Only generate the route topology here. \n",
                    "            routes = generate_route_system(num_routes, G_city, demand_sampler)\n",
                    "            \n",
                    "            if USE_PARALLEL:\n",
                    "                # Duck-typing: Mock the JeepSystem to bypass the strict __init__ validation.\n",
                    "                # The parallel runner only reads the `.routes` property from this container.\n",
                    "                class MockJeepSystem:\n",
                    "                    def __init__(self, r):\n",
                    "                        self.routes = r\n",
                    "                \n",
                    "                env = SimEnvironment(\n",
                    "                    tg=None, \n",
                    "                    yaml_file=batch_yaml,\n",
                    "                    jeep_system=MockJeepSystem(routes),\n",
                    "                    sampler=demand_sampler,\n",
                    "                    delete_yaml_when_done=(rep == reps - 1) \n",
                    "                )\n",
                    "            else:\n",
                    "                # If sequential, we MUST build the full graphs in the main thread\n",
                    "                tg = build_travelgraph(G_city, batch_yaml, routes)\n",
                    "                jeep_system = generate_jeep_system(routes, num_routes * 10, demand_sampler, tg)\n",
                    "                env = SimEnvironment(\n",
                    "                    tg=tg, \n",
                    "                    yaml_file=batch_yaml,\n",
                    "                    jeep_system=jeep_system,\n",
                    "                    sampler=demand_sampler,\n",
                    "                    delete_yaml_when_done=(rep == reps - 1) \n",
                    "                )\n",
                    "                \n",
                    "            envs.append(env)\n",
                    "            \n",
                    "    # --- EXECUTION PHASE (UNMUTED) ---\n",
                    "    try:\n",
                    "        if USE_PARALLEL:\n",
                    "            sim_results = run_simulations_parallel(envs)\n",
                    "        else:\n",
                    "            sim_results = []\n",
                    "            for env in envs:\n",
                    "                # Mute the noisy simulation tick loop if running sequentially\n",
                    "                with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):\n",
                    "                    sim = run_simulation_env(env)\n",
                    "                    sim_results.append(sim.evaluate_fitness())\n",
                    "                    \n",
                    "    except Exception as e:\n",
                    "        print(f\"\\n[FATAL ERROR] Simulation runner failed: {e}\")\n",
                    "        return 1.0 # Return max variance to skip this bad parameter cleanly and prevent a hard crash\n",
                    "        \n",
                    "    fitness_scores = [res.score for res in sim_results if res is not None]\n",
                    "    \n",
                    "    # --- MEMORY CLEANUP ---\n",
                    "    del envs\n",
                    "    del sim_results\n",
                    "    del G_city\n",
                    "    del demand_sampler\n",
                    "    gc.collect() \n",
                    "    \n",
                    "    if not fitness_scores:\n",
                    "        return 1.0 \n",
                    "        \n",
                    "    mean_fitness = np.mean(fitness_scores)\n",
                    "    std_fitness = np.std(fitness_scores)\n",
                    "    \n",
                    "    cv = (std_fitness / mean_fitness) if mean_fitness > 0 else 1.0\n",
                    "    return cv"
                ]
                cell["source"] = new_source

            # Identify search algorithm cell
            elif "def find_optimal_spt" in source_text:
                print("Updating search cell (find_optimal_spt and find_optimal_ticks)...")
                new_source = [
                    "CV_THRESHOLD = 0.05  # 5% relative variance limit (literature backed)\n",
                    "\n",
                    "def find_optimal_spt(num_routes, pass_rate):\n",
                    "    \"\"\"\n",
                    "    Finds MAXIMUM seconds_per_tick while keeping CV <= 0.05.\n",
                    "    Tested against a high tick count (4000).\n",
                    "    \"\"\"\n",
                    "    fixed_ticks = 4000\n",
                    "    coarse_grid = [10, 30, 60, 120, 180, 240, 300]\n",
                    "    \n",
                    "    print(\"\\n    [Coarse Sweep SPT]\")\n",
                    "    best_coarse = 10\n",
                    "    for spt in coarse_grid:\n",
                    "        cv = evaluate_stability(spt, fixed_ticks, num_routes, pass_rate)\n",
                    "        print(f\"      - SPT: {spt:3d}s | CV: {cv:.4f} (Threshold: {CV_THRESHOLD:.2f}) -> {'PASS' if cv <= CV_THRESHOLD else 'FAIL'}\")\n",
                    "        if cv <= CV_THRESHOLD:\n",
                    "            best_coarse = spt\n",
                    "        else:\n",
                    "            break # Variance spiked, stop searching higher\n",
                    "            \n",
                    "    if best_coarse == 300: return 300 # Maxed out\n",
                    "    \n",
                    "    # Phase 2: Fine Sweep (zoom in on the bracket between best_coarse and the failure point)\n",
                    "    fine_step = 10\n",
                    "    fine_grid = range(best_coarse + fine_step, best_coarse + 60, fine_step)\n",
                    "    \n",
                    "    print(\"    [Fine Sweep SPT]\")\n",
                    "    best_fine = best_coarse\n",
                    "    for spt in fine_grid:\n",
                    "        cv = evaluate_stability(spt, fixed_ticks, num_routes, pass_rate)\n",
                    "        print(f\"      - SPT: {spt:3d}s | CV: {cv:.4f} (Threshold: {CV_THRESHOLD:.2f}) -> {'PASS' if cv <= CV_THRESHOLD else 'FAIL'}\")\n",
                    "        if cv <= CV_THRESHOLD:\n",
                    "            best_fine = spt\n",
                    "        else:\n",
                    "            break\n",
                    "            \n",
                    "    return best_fine\n",
                    "\n",
                    "def find_optimal_ticks(num_routes, pass_rate):\n",
                    "    \"\"\"\n",
                    "    Finds MINIMUM num_ticks while keeping CV <= 0.05.\n",
                    "    Tested against a low seconds_per_tick (10).\n",
                    "    \"\"\"\n",
                    "    fixed_spt = 10\n",
                    "    coarse_grid = [100, 500, 1000, 2000, 3000, 4000, 5000]\n",
                    "    \n",
                    "    print(\"\\n    [Coarse Sweep Ticks]\")\n",
                    "    best_coarse = 5000\n",
                    "    for ticks in reversed(coarse_grid):\n",
                    "        cv = evaluate_stability(fixed_spt, ticks, num_routes, pass_rate)\n",
                    "        print(f\"      - Ticks: {ticks:4d} | CV: {cv:.4f} (Threshold: {CV_THRESHOLD:.2f}) -> {'PASS' if cv <= CV_THRESHOLD else 'FAIL'}\")\n",
                    "        if cv <= CV_THRESHOLD:\n",
                    "            best_coarse = ticks\n",
                    "        else:\n",
                    "            break # Variance spiked because duration is too short\n",
                    "            \n",
                    "    if best_coarse == 100: return 100 # Minimized fully\n",
                    "    \n",
                    "    # Phase 2: Fine Sweep (zoom in decreasingly)\n",
                    "    fine_step = 100\n",
                    "    fine_grid = range(best_coarse - fine_step, max(100, best_coarse - 1000), -fine_step)\n",
                    "    \n",
                    "    print(\"    [Fine Sweep Ticks]\")\n",
                    "    best_fine = best_coarse\n",
                    "    for ticks in fine_grid:\n",
                    "        cv = evaluate_stability(fixed_spt, ticks, num_routes, pass_rate)\n",
                    "        print(f\"      - Ticks: {ticks:4d} | CV: {cv:.4f} (Threshold: {CV_THRESHOLD:.2f}) -> {'PASS' if cv <= CV_THRESHOLD else 'FAIL'}\")\n",
                    "        if cv <= CV_THRESHOLD:\n",
                    "            best_fine = ticks\n",
                    "        else:\n",
                    "            break\n",
                    "            \n",
                    "    return best_fine"
                ]
                cell["source"] = new_source
                
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
        
    print("Notebook updated successfully.")

if __name__ == "__main__":
    main()
